[package]
name = "stl"
version = "0.1.0"
authors = ["Vishal Patil <vishpat@gmail.com>"]
license = "MIT"
homepage = ""
repository = ""
documentation = ""
description = """
RUST crate to parse STL files used for 3D printing.
"""

[dependencies]
byteorder = "1.2.1"
